// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Autograph: typeof import('./components/common/Autograph.vue')['default']
    Calendar: typeof import('./components/calendar/Calendar.vue')['default']
    EmptyCommon: typeof import('./components/common/EmptyCommon.vue')['default']
    Loading1: typeof import('./components/quin/qiun-loading/loading1.vue')['default']
    Loading2: typeof import('./components/quin/qiun-loading/loading2.vue')['default']
    Loading3: typeof import('./components/quin/qiun-loading/loading3.vue')['default']
    Loading4: typeof import('./components/quin/qiun-loading/loading4.vue')['default']
    Loading5: typeof import('./components/quin/qiun-loading/loading5.vue')['default']
    Navbar: typeof import('./components/common/navbar.vue')['default']
    QiunDataCharts: typeof import('./components/quin/qiun-data-charts/qiun-data-charts.vue')['default']
    QiunError: typeof import('./components/quin/qiun-error/qiun-error.vue')['default']
    QiunLoading: typeof import('./components/quin/qiun-loading/qiun-loading.vue')['default']
    Reassign: typeof import('./components/taskOperation/Reassign.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabarContaions: typeof import('./components/common/TabarContaions.vue')['default']
  }
}
